name: 'niaid'
description: 'Switches AWS credentials to change authentication between Monarch Spaces accounts'
author: 'niaid'
inputs:
  account: 
    required: true
    description: 'Monarch Spaces account to switch to'
runs:
  using: 'node12'
  main: 'dist/index.js'
