name: 'niaid'
description: 'Switches AWS credentials to change authentication between Monarch Spaces accounts'
author: 'niaid'
inputs:
  account: 
    required: true
    description: 'Monarch Spaces account to switch to (dev, qa, stage, prod, mgmt)'
runs:
  using: 'node20'
  main: 'dist/index.js'
