name: Dependabot Alerts to Issues

on:
  schedule:
    - cron: '0 0 * * *' # run daily
  workflow_dispatch:

jobs:
  alerts-to-issues:
    uses: niaid/trellaction-workflow/.github/workflows/alerts-to-issues.yml@main
    secrets:
      repo_token: ${{ secrets.REPO_TOKEN }}