name: Dependabot Alerts to Issues

on:
  # schedule:
  #   - cron: '0 0 * * *' # run daily
  workflow_dispatch:

jobs:
  alerts-to-issues:
    uses: niaid/trellaction-workflow/.github/workflows/alerts-to-issues.yaml@main
    with:
      custom_labels: "Scope: Security,O&M Task"
      priority_prefix: "Priority:"
    secrets:
      repo_token: ${{ secrets.REPO_TOKEN }}
