name: Test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      account: 
        description: "Which account are you switching to?"
        default: dev

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Verify mgmt account
      run: aws s3 ls
    - name: Test action!
      uses: ./
      with:
        account: ${{ github.event.inputs.account || 'dev'}}
    - name: Verify target account
      run: aws s3 ls
    - name: Test action!
      uses: ./
      with:
        account: mgmt
    - name: Verify mgmt account again
      run: aws s3 ls